
* CLOJURE/GCOS
backtracing pre-allocated exceptions.   
javascript cost of throwing exceptions.

-> compile to a loop + jump table (case)

code code generation for more targets

all based on scoring columns 

predicate dispatch/ open extension. 

- reorder the tests
- add new pattern type.
- sequences (only head & tail)
- heade & tail
- extract pattern matrix
  each row values/to match against them

- find which expression should be first tested & reorder the test
- pattern type [ pass all rows that match] 

  
** to understand
- [x] backtracing pre-allocated exceptions.
- how case work/ -> compiling 
- [x] sometimes we use defrecord, and sometimes deftype, 
really really what's the difference 
** notes
*** NYC clojure meetup:  https://vimeo.com/27860102
- dispatching on type.
- extend the type.
- dispatch on patterns...[structural mathcing]
- extend pattern matching.
- add disptaches after the fact, without modifiying the original code.
- decision trees
  (set pattern -> tree)  . moving through branching till hit leafs
  
  backtracking automata (retest cases)

  lazy, only columns that must be tested will be tested
  - decide which are worth
  - top down 
  - optimize in memory

** GOC/opening Message to David
  Hello @David! First, I would really want to thank you for your work
  on Clojure/Clojurescript (The Dream Machine.) It trully brings
  inspiration. I have watched both of your talks on core.match, I've
  also read the wiki and Maranget paper, though I need to read it many
  times more. I'm also studying core.match code (compiling
  notes/questions) I would really really love to have the privelege of
  spending my full time thinking and working on it under your
  mentorship. I'm 3rd (and last) year student (at U of Winnipeg,
  Canada) though on school they didn't not expose us to FP (which is
  sad), but luckily in the previous years I've had contact with LISP,
  and it just made sense to how things ought to be. I've gone through
  SICP last summer while laboring, and also through little schemer as
  per your recommendation and HTDP before turning my attention
  exclusively toward Clojure starting from previous December, though I
  have played with it before and kept following the community.
  core.match is awesome and I want to do my best and make it compile
  better for Clojurescript under your mentorship. Thank you for
  reading this. It all started with "syntactical daydreaming" :)  My
  name is Sifou, my github is https://github.com/bsifou:  and I'm
  https://twitter.com/bsifou_ on twitter.

*** v2
  Hello @dnolen! First, I would really want to thank you for your work
  on Clojure/Clojurescript (The Dream Machine.) It truly brings
  inspiration. I have watched both of your talks on core.match, I've
  also read the wiki and Maranget paper, though I need to read it many
  times more. I'm also studying core.match code (compiling
  notes/questions) I would really really love to have the privilege of
  spending my full time thinking and working on it under your
  mentorship. I'm 3rd (and last) year student (at U of Winnipeg,
  Canada) though on school they didn't not expose us to FP (which is
  sad), but luckily in the previous years I've had contact with LISP,
  and it just made sense to how things ought to be. I've gone through
  SICP last summer while labouring, and also through little schemer as
  per your recommendation and HTDP before turning my attention
  exclusively toward Clojure starting from previous December, though I
  have played with it before and kept following the community.
  core.match is awesome and will be cool if it gets to compile better
  for Clojurescript. Thank you for reading this. It all started with
  "syntactical daydreaming" :)  My name is Sifou, my github is
  https://github.com/bsifou, and I'm https://twitter.com/bsifou_ on
  twitter.
  
** questions about the algorithm/general
- how do we know, that a pattern actually
  filter a value (occurence, how the code that
  []*A* maybe when compiling the pattern in to something that goes into
  an -if- & then the -then- part the specialize matrix result? which
  also get's compilied????
does that looks like?
- what are cases from Special matrix?

** question about the paper
- what does he means by head constructor?
- what make a set of constructors a complete signature?
** questions about the code
- so what occurences look like
  they seem to be associated with matrix
- on line 2070 in emmit-matrix we seem to process-vars twice?
  it's local binding is _vs_
- [x] if the ocr-expr is (+ 1 2) doest it become 3 when 
  emmited,
  *A* it doesn't. it get bound to ocr- in a let scope.
- how it's made sure that width always return the width 
of matrix, if rows are not of same length?, error?
  *A* check-pattern takes care of it, called from
  check-matrix-args, before compiling in clj-form
- what's the nature of ps in pattern row, a vector?
- why definterface, and not defprotocol
  for IExistentialPattern, IPseudoPattern?
  *A* to be able to ask instance? 
- why MapKeyPattern, which is IExistentialPattern
  get's score of 1, others gets 2?
- why MapKEyPattern is a record and not a deftype, like 
  the other patterns?
- how can we signal that we have chosen a column and not take it
  twice (in compile, :813)
- patternRow takes bindings, what does that look like
  [?] *A* maybe it's related to the as thing?, cause when specializing
  we added it there 
  I might need to see where it is created, (emmit somthing?)
- when do the binding get applied (what func responsible for it),
  before the pattern get's compiled (using the ocr) in an if test? 
- where is the _cond_ that get produced by Switch node, i don't see it
  in the macro-expansion
  *A* Hmm! maybe because cond-> gets macro-expanded to bunch of if's
  in when expanded!
- LeafNode & BindNode why is there binding related stuff to LeafNode,
  what does BindNode do then!!! 

- !!! when do we get a vector of matrixes that get passed to `cases` when
  we split the matrix? 

** to discuss with David
   - ask him about recur
   - provide for him a description of how all things fit together,
     and if I have understood wrong
   - suggest if it's possible to do incremental updates, where we
     start with a simple pattern, support for it the loop compilation
     before moving to others.
   - give a comparison of how the code expands now, and how it should
     after implementing this feature/ also provide pictorial *graph* as
     per the paper. 
   - get suggestion from him of other resources to read/still from
   - is tools.anaysers will be usefull for us?

   - Hi, I'm sorry at first I didn't read about how Clojure
     contribution works, but now I know.  I've signed CA & submitted
     the typo patch (first ever) To better understand you, I've looked
     a bit into how ColjureScript compilation process works and also
     on how go macros are implemented in core.async, though it will
     take me a very long time to "get it." I have a question that is
     maybe dumb one, is tools.anayser can be helpfull to us in
     core.match? I'm currently thinking on how to find rep for matrix
     patterns as one map that allow us to re-use most of the code
     logic, is that in right direction?  Thank you :)

     - if we can use clojure specs
     - @dnolen Hi!  I hope you're feeling better :) Thank you your
       feedback.  for When I heard about clojure.tools & AST stuff, I
       was thinking about somehow extending it. But now things are bit
       more clearer, I think it's bit not straightforward how to do
       it. I will keep studying it, it's cool how it works and also
       for inspiration.  Spec'ing the AST will be awesome! I think we
       can spec our matching syntax will get a a decent rep and maybe
       after that we can enrich it for our algorithm to get `dag` [at
       this point it's not clear to me how it will look like, & how
       code get generated from it] The next days I will spend more
       time looking in the details & breaking things appart and figure
       out how to re-use what we have. I hope I'm on right
       track. @dnolen I have question (maybe it's dumb), since it's
       important to keep things open for extension, is it also
       important to preserve to same interface we currently use to
       extend patterns?

*** irc
        @dnolen I have signed CA, and submitted typo fix (first patch
        ever) MATCH-119
        
** thoughts on how to solve it    
- Somehow change the implemntatioon of  IPatternCompile
  in each pattern? -- need to get back to the paper for that.
- so you loop through the condidtates that comes out form
  SpecializeMatrix (tests) when compiled those gets spit out as
  clauses in SwitchNode and whichever works jump right to that
  SwitchNode, I mean the output of it.
- David advised me to think about data rep of the patterns, to somehow
  plug that before code generation, which means I have to
- we have clojure code -> deftypes (patterns matrix) -> algorithm (compile |
  nodes) -> nodes (deftypes)  -> /maybe need a middle step? (data)/ -> clojure code [to be replace]

  (we have to replace the code generation step)

- can we use (crazy) clojure.anayser and extend it or something! I
  mean in the since we are feeding clojure data there!

- According to the presentation I've watched what it does is: (halgari)
  - clojure code (s-expressoin) -> data represetation -> manipulate
    and stufff (they call them analyser passes)->
    to-clj -> clojure code again (templating) 

- I have to find an intermediate representation to compile a match to
  it... 
- introduce reader-macros? 

- We currently have patterns represented as `deftypes`, and during the
  decision tree generation, to specialize matrix on pattern, we pass
  the whole matrix to that pattern method which knows how to give us
  an other matrix. We represent pattern matrix as data only, when we
  need to specialize on it, we can pass to function with other
  information as second argument (pattern we want to specialize on) to
  sculpt that data in right way (produce a new matrix rep.)

    NB. we seem to be always specializing on first occurence.

- Remove the redunduncy, there are many functions that we call many
  times specifically `regroup-keywords`

- pattern matrix will look like this

- dispatch matrix specialization, on the type of pattern in a row

;; {
;;  :occurences {}
;;  :rows [{:patterns [] :action} {:patterns [] :action}]
;;  }
;; a pattern is {:type :wild-card-pattern :binding  :}
  
*** desgin of IR
;; specializing is mostly about introducing new cols
;; cols 

;; matrix:

;; occurences: (they only get tested once)
;; rows vecotr of vectors
;; 

;; pattern type
;; 

;; dag


;; 

** to consult:
   - some data stuff talk (maybe Rich) / https://www.youtube.com/watch?v=rI8tNMsozo0
   - htdp, has something nice to say about data (check how things done
     there) (Racket maybe)
   - rich hicky talk (about clojure pro to pro (or somehting like
     that...)
   - the magic project
   - core async & the use of go macro???
     

** TODO
- map the macro exampnd result to graph
- continue reading source code, from pattern emmiting till the
  compilation
  - understand how vector-pattern works 
  patterns though! 
- [x] get to the bottom of *recur-present*!
- play with analyser/clojurescript AST stuff...
- [x] continue reading on dynmique programming aspects...
- understood better dealy & how it works... (
 - what's the difference between clj/reader & tools.analyzer.reader? 
*** read the code 
** what I've done today:
- <2017-03-06 Mon>
  - I've understood what it means to expand matrix
- <2017-03-07 Tue>
  - read-up more on prtocols, multimethods, pholymorphism...
  - java/clojure got more details pinned down.
<2017-03-08 Wed>
 - more on polymorphism, protocols quicrks... (we use them heavily
   here)
 - proxy/reify once and for all... (hopefully)
 - clarified the stuff :) great thread
   https://groups.google.com/forum/#!msg/clojure/pZFl8gj1lMs/qVfIjQ4jDDMJ
<2017-03-13 Mon>
- read more about Rich writings on clojure/data structures
- understood the ants demo
- checked core.async / didin't understand much :( / probably the one
  thing i've go is how to generate code based on cases 
- read the paper more
- <2017-03-15 Wed>
  - watched Rich hickey talk on design
  - read rational/clojure philosphy (clojure.org)
  - discuessed what I will be focusing on with David
  - read about AST/clojure.tools.analyzer & stuff
  - I will be working on
  - Read wiki on aspect of dynmique programming: polymorishism/reflection/macros/
  - played a bit with clojure reflection API
  <2017-03-16 Thu>
  - better understood lazy-seq (took half day)
  - spec/ generative testing  (watched 2 takls + screen-cast)
   <2017-04-16 Thu>
     :TODO:
   - read the paper, write the first draft of proposal,
   - read clojure.spec (on clojure.org) (maybe rewatch Rich talk)
   - put the other stuff on the quee... (???)
     :DID:
    - finished playing & watching Stuart Halloway talk on specre
    - watched an other talk by Stuart halloway on simplicity &
      breaking things appart & not conflating & reuse
<2017-03-18 Sat>
- investigating on why we use :occurence-type 
** related-question on clojure
- Why when we implemented Clojure.lang.IpresistentCollection we only
  implemented (cons, equiv) but not empty and count, even though we've
  implemented cons, we can't use it... we have to use conj. And also
  if if we implement count even without using seq in our
  implementation we must also implement seq? Why is that!

- Why we can extend some part of protocol/interface?
- what is proxy class/ and how it relates to the one in Java.. hmm..



** notes about the code
*** meta on occurences:
    - :occurence-type -> any of :seq :vector :map :default
      :bind-expr (when we  non-symbol expr provided to match macro)
      :tag
      :index 
      ---------
      :map-sym
      :key
      ---------
      :vec-sym
*** meta on patterns
    :as
    :offset
    :only 
** observations
- so pretty much every Pattern is a deftype?
  but MapKeyPattern which is a record, why?  
- so pretty much each pattern knows how to compile
itself (huh?), and how to produce specialize-matrix
(needs to clear that!)
- when we create patternrow, binding is [] wtf! 
- The cycle emit-pattern -> emit-pattern-for-syntax -> emit-pattenrs->
  [loop again]
- also for litteral-pattern gotta be qualified by *quote* in seq? How
  is that!?
- so we get one-to-one mapping from syntax to patterns objects
  [patter[patttern] [pattern] -> patternrow
- in seqPattern, it just compiles to (seq ocr) how to do you check 
  that the pattern matches the damn thing (ocr?)
- so IPatternCompile code gets stuck into an if test, hmm!
- leaf-bind-expr, what a strange name, has to do with the occurence
  and it's symbol and binding? (this is getting confusing!) 
- so the switchNode is responsile for the (if (test [which is a
  pattern compile)) and concatenating the the conds with (if :else
  backtrack)
- with recur, we use backtrack, without we somehow get to use
  default!!! [the who thing is muddy!)
- actions must implement INodeCompile protocol they come right after
  the (if test), we have FailNode, LeafNode, BindNode [which does do much,
  delegate the other two nodes), that gives us
  something when (n-to-clj ) hmm, food for thought....
- pseudo-pattern are func app :<< and :or patterns, we expand the
  matrix on it.
- when we expand on Orpattern, we introduce extra rows
  but when we expand on appPattern we introduce new occurence to the
  matrix, with {:bind-expr ~(form first-occ)
- so groupable is being used for checking if two pattern are equal,
  hmm.
- So to match against appPatern, we introduce  a new occurence, apply
  the form to it, and then change each row such that we add a new
  wild-card pattern after the patern to match kinda always match, let
  the scoring system takes care of it.
- this whole thing, where we have types, to make new type values from
  previous, we have to do destructring, but because we are using
  custom type values we have to destructre everything by hand, no
  clojure support ;-)  Feels lot like Racket, feels good :) 
*** deftypes: [patterns]
   PatternRow 
   WildcardPattern 
   LiteralPattern 
   SeqPattern
   MapPattern
   VectorPattern
   OrPattern 
   GuardPattern 
   AppPattern
   PredicatePattern
*** defrecords [Nodes]
    LeafNode
    FailNode
    BindNode 
    SwitchNode 
    PatternMatrix
    RestPattern
    MapKeyPattern

* Insigths/day
-  we are on a race, and the only way to get ahead, is to learn (get
  used) to lead  and not follow.
  
- I need to look ahead, how the thing should look like, kinda of
  moving forward & then working my way backward.   

** design / rich hickey talk
   - take things appart & put them together 
   - order, infomration, solution
   - find the actual problems (needs to problems)
   - devide -> things I know / things I don't
   - seperate the cause from the symptoms
   - unstated requirement (attributes that not supposed to have)
   - time (order, queues)
   - 

I want to appologize for not being able to make it to class today, as
am not feeling too well. I'm sure I've missed some thought provoking
ideas and intersting discussion. I'm looking forward for next class &
hope to make it. Thank you.









* Questions to david 
- the quirks of *recur-present*
- if it's possible to use the read-macro for clojurescript-stuff
- 
  


* Proposal
** Abstract
*** stuff
    the work will be on adapting & refactoring the algorithm
    functions, to operate on our matrix rep, as it currently depends
    on the `deftypes` of different. These include pattern scoring to
    choose a column to specialize on.
    
    We will be adapting clojure.spec to parse & check the syntax of
    our pattern matching macro, this gives us a complete transparent
    data reprentation of the rows of patterns. This will gives us more
    flexibility at manipulating and applying our algorithm wihich will
    result in a decision tree, also will be represented using regular
    but powerfull clojure data-structures. I think, our work will also
    be consiting of 3 composable steps (matrix-emssion, takes matrix
    data from user (macro) and turn in into a rep that get fed to next
    step, algorithm-application `compile`, which will be be producing
    DAG rep of clojure code to be generead in the next step.

** timeline
- work on specifying the specs of what our matching macro 
  (make sure it's comlete & harmonic)
- work on adapting our algorithm to our new rep, this include any
  adding/comuting an neccesary information to our rep that algorithm
  need it to work in harmony. 
- 
**  Delivarables 
